### ISSUE TITLE
image list sync failed

### ISSUE THREAD

**Issue by willzhang** [labring-actions/cluster-image-docs#58]
Auto schedule action for aliyun lists looks like failed, docker lists ok.

https://github.com/labring-actions/cluster-image-docs/actions/runs/6822288364/job/18554089187

![image](https://github.com/labring-actions/cluster-image-docs/assets/33590311/a43d7caf-914b-4c31-a839-6de3f7033d49)

**Comment by cuisongliu** [comment]
可能会有延时，就是相当于镜像还没有同步到阿里云,所以文档拉不下来。下次同步就好了。
